version: '3.1'
services:
  mongo:
    image: mongo:5.0
    container_name: "mongo_commerce"
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - './:/app'
    ports:
      - 27017:27017
